# Generated by Django 3.0.8 on 2020-08-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('abstracto', models.TextField()),
                ('imagem', models.ImageField(upload_to='post_pics')),
                ('referencia', models.URLField(default='none.com', max_length=500)),
            ],
        ),
    ]
